# Generated by Django 4.0.4 on 2022-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='descripcion')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('precio', models.FloatField(verbose_name='precio')),
            ],
        ),
    ]
